### ISSUE TITLE
Bastion: Primary Fire Damage

### ISSUE THREAD

**Issue by DpsDoomMain** [MaxwellJung/ow1_emulator_issues#225] opened 2023-09-21 21:44 UTC
Damage was increased to 25 in overwatch 2 and in overwatch 1 it was 20

**Comment by MaxwellJung** [comment] 2023-09-21 23:18
His firerate is different. I plan to adjust his primary fire damage so that the amount of damage he deals in a given time is consistent to OW1. Also, duplicate of #79

**Closed by MaxwellJung** 2023-09-21 23:18 UTC
